add_rules("mode.debug", "mode.release")

target("SalmonActions")
    add_rules("qt.shared")
    add_frameworks("QtCore", "QtGui", "QtWidgets", "QtTest")
    add_defines("SalmonActions_LIB")
    add_headerfiles("include/*.h")
    add_includedirs("include")
    add_files("resource/*.qrc") 
    add_files("include/*.h") 
    add_files("src/*.cpp") 
 
target("test") 
    set_default(false)
    add_rules("qt.console")
    add_includedirs("include")
    add_frameworks("QtCore", "QtGui", "QtWidgets")
    add_deps("SalmonActions")
    add_files("test/*.cpp")
